name: Package

env:
  XCODE_VERSION: 14.2

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Build
      uses: nick-fields/retry@v2.8.2
      with:
        retry_on: error
        timeout_minutes: 10
        max_attempts: 3
        command: swift build ${RUNNER_DEBUG:+-v}

    - name: Test
      uses: nick-fields/retry@v2.8.2
      with:
        retry_on: error
        timeout_minutes: 10
        max_attempts: 3
        command: swift test ${RUNNER_DEBUG:+-v}

  publish-documentation:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout `docs` as worktree
      run: |
        git worktree prune
        git fetch origin docs
        git worktree add --checkout docs origin/docs

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Reset package cache
      run: swift package reset ${RUNNER_DEBUG:+-v}

    - name: Reset public directory
      run: |
        rm -rf docs/public
        mkdir docs/public

    - name: Generate documentation
      uses: nick-fields/retry@v2.8.2
      with:
        retry_on: error
        timeout_minutes: 10
        max_attempts: 3
        command: |
          export TOOLCHAINS=swift
          export DOCC_JSON_PRETTYPRINT=YES
          swift package \
            --allow-writing-to-directory docs/public \
            generate-documentation \
            --output-path docs/public \
            --target Flock \
            --include-extended-types \
            --source-service github \
            --source-service-base-url https://github.com/qasim/Flock/blob/main \
            --checkout-path $GITHUB_WORKSPACE \
            --disable-indexing \
            --transform-for-static-hosting \
            ${RUNNER_DEBUG:+-v}

    - name: Publish documentation
      run: |
        cd docs
        git add .
        if [[ `git status --porcelain` ]]; then
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Regenerate documentation at $GITHUB_SHA"
          git push origin HEAD:docs
        fi
