name: Package

env:
  XCODE_VERSION: 14.2

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Build
      run: swift build -v

    - name: Test
      run: swift test -v

  publish-documentation:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Reset package cache
      run: swift package reset

    - name: Reset public directory
      run: rm -rf Documentation/public/*

    - name: Generate documentation
      run: |
        export TOOLCHAINS=swift
        swift package \
          --allow-writing-to-directory Documentation/public \
          generate-documentation \
          --output-path Documentation/public \
          --target Flock \
          --include-extended-types \
          --disable-indexing \
          --transform-for-static-hosting

    - name: Publish documentation
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git switch -C docs
        git add .
        git commit -m "Generate documentation"
        git push -f origin docs
