name: Package

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  test:
    runs-on: macos-12

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.1

    - name: Build
      run: swift build -v

    - name: Test
      run: swift test -v
