name: Package

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  test:
    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: swift build -v

    - name: Test
      run: swift test -v
